"""
SPICE网表生成器
负责将电路数据转换为SPICE网表格式
"""

import logging
from typing import Dict, List, Tuple, Optional, Any
from scr.data.data_layer import Component, Connection, ComponentType

logger = logging.getLogger(__name__)


class NetlistGenerator:
    """SPICE网表生成器"""
    
    def __init__(self, node_assigner=None):
        self.logger = logger
        self.wire_resistance = 0.001  # 导线电阻（Ω）
        self.node_assigner = node_assigner  # 可选：使用NodeAssigner获取节点信息
    
    def generate(self, components: Dict[str, Component], 
                 connections: Dict[str, Connection],
                 node_map: Dict[str, int]) -> str:
        """
        生成完整的SPICE网表
        
        参数:
            components: 元件字典
            connections: 连接字典
            node_map: 节点映射 {component_id: node_id}
        
        返回:
            SPICE网表字符串
        """
        try:
            netlist = "* VR Electric Lab Circuit Netlist\n"
            netlist += "* Generated by NetlistGenerator\n\n"
            
            # 1. 生成元件行
            component_lines = self._generate_component_lines(components, node_map)
            netlist += component_lines
            
            # 2. 生成导线行
            wire_lines = self._generate_wire_lines(components, connections, node_map)
            if wire_lines:
                netlist += "\n* Wire connections\n"
                netlist += wire_lines
            
            # 3. 添加分析指令
            netlist += "\n* Analysis commands\n"
            netlist += ".tran 0.1 1\n"
            netlist += ".end\n"
            
            self.logger.debug(f"生成的网表:\n{netlist}")
            return netlist
            
        except Exception as e:
            self.logger.error(f"网表生成失败: {e}", exc_info=True)
            return ""
    
    def _generate_component_lines(self, components: Dict[str, Component], 
                                  node_map: Dict[str, int]) -> str:
        """生成所有元件的SPICE行"""
        lines = "* Circuit components\n"
        
        for comp_id, component in components.items():
            if component.type == ComponentType.GROUND:
                continue  # 接地不需要单独的SPICE行
            
            line = self._generate_component_line(component, components, node_map)
            if line:
                lines += line + "\n"
        
        return lines
    
    def _generate_component_line(self, component: Component, 
                                 all_components: Dict[str, Component],
                                 node_map: Dict[str, int]) -> str:
        """
        为单个元件生成SPICE行
        
        格式:
        - 电压源: V<name> <+node> <-node> <voltage>
        - 电阻: R<name> <node1> <node2> <resistance>
        """
        comp_id = component.id
        
        if component.type == ComponentType.POWER_SOURCE:
            """
            电压源: 优先使用 NodeAssigner 给出的 (正极, 负极) 节点对，
            若没有可用的节点对，再退回到旧逻辑（正极=node_map，负极=0）。
            """
            node_positive: int
            node_negative: int

            # 1) 如果有 NodeAssigner，就直接用 get_component_nodes 的结果
            if self.node_assigner:
                nodes = self.node_assigner.get_component_nodes(comp_id, all_components)
                if nodes:
                    node_positive, node_negative = nodes
                else:
                    # 回退到旧行为
                    node_positive = node_map.get(comp_id, 1)
                    node_negative = 0
            else:
                # 旧逻辑：正极来自 node_map，负极固定接地
                node_positive = node_map.get(comp_id, 1)
                node_negative = 0  # 负极接地

            voltage = component.parameters.get('voltage', 5.0)
            return f"V{comp_id} {node_positive} {node_negative} {voltage}"
        
        elif component.type == ComponentType.RESISTOR:
            # 电阻：需要确定两个节点
            nodes = self._get_resistor_nodes(component, all_components, node_map)
            if nodes:
                node1, node2 = nodes
                resistance = component.parameters.get('resistance', 1000.0)
                return f"R{comp_id} {node1} {node2} {resistance}"
        
        return ""
    
    def _get_resistor_nodes(self, resistor: Component, 
                           all_components: Dict[str, Component],
                           node_map: Dict[str, int]) -> Optional[Tuple[int, int]]:
        """
        确定电阻的两个节点
        
        策略:
        1. 如果有NodeAssigner，优先使用它的get_component_nodes方法
        2. 否则使用原有逻辑（向后兼容）
        """
        # 优先使用NodeAssigner
        if self.node_assigner:
            nodes = self.node_assigner.get_component_nodes(resistor.id, all_components)
            if nodes:
                return nodes
        
        # 降级方案：使用原有逻辑
        resistor_node = node_map.get(resistor.id)
        if resistor_node is None:
            return None
        
        # 找到所有节点编号小于电阻节点的元件
        # 这些是电阻的"上游"元件
        upstream_nodes = []
        for comp_id, comp_node in node_map.items():
            if comp_node < resistor_node and comp_id != resistor.id:
                component = all_components.get(comp_id)
                if component and component.type != ComponentType.GROUND:
                    upstream_nodes.append(comp_node)
        
        if upstream_nodes:
            # 输入节点是最大的上游节点（最接近的上游）
            input_node = max(upstream_nodes)
            output_node = resistor_node
        else:
            # 如果没有上游节点，可能是第一个电阻，连接到电源
            # 找到电源节点
            power_node = None
            for comp_id, component in all_components.items():
                if component.type == ComponentType.POWER_SOURCE:
                    power_node = node_map.get(comp_id, 1)
                    break
            
            input_node = power_node or 1
            output_node = resistor_node
        
        return (input_node, output_node)
    
    def _generate_wire_lines(self, components: Dict[str, Component],
                            connections: Dict[str, Connection],
                            node_map: Dict[str, int]) -> str:
        """
        生成导线连接的SPICE行
        
        规则:
        1. 最后一个元件到接地需要导线
        2. 其他情况根据连接关系判断
        """
        wire_lines = ""
        wire_count = 1
        processed = set()
        
        for conn_id, connection in connections.items():
            comp1 = components.get(connection.component1_id)
            comp2 = components.get(connection.component2_id)
            
            if not comp1 or not comp2:
                continue
            
            # 避免重复处理
            conn_key = tuple(sorted([connection.component1_id, connection.component2_id]))
            if conn_key in processed:
                continue
            processed.add(conn_key)
            
            # 检查是否需要导线（传递完整的components字典）
            wire_spec = self._check_wire_needed(comp1, comp2, node_map, components)
            if wire_spec:
                node1, node2 = wire_spec
                if node1 != node2:
                    wire_lines += f"RW{wire_count} {node1} {node2} {self.wire_resistance}\n"
                    wire_count += 1
        
        return wire_lines
    
    def _check_wire_needed(self, comp1: Component, comp2: Component,
                          node_map: Dict[str, int],
                          all_components: Dict[str, Component]) -> Optional[Tuple[int, int]]:
        """
        检查两个元件之间是否需要导线
        
        返回: (node1, node2) 如果需要导线，否则返回None
        
        规则：
        1. 接地连接：如果元件连接到接地，且元件的输出节点不是0，需要导线
        2. 并联电路：元件的节点对已经正确，不需要导线
        3. 串联电路：元件之间的连接已经在节点对中处理，不需要导线
        """
        # 获取两个元件的节点
        node1 = node_map.get(comp1.id)
        node2 = node_map.get(comp2.id)
        
        if node1 is None or node2 is None:
            return None
        
        # 规则1：接地连接
        # 检查是否有元件连接到接地，且该元件的输出节点不是0
        if comp1.type == ComponentType.GROUND:
            # comp2连接到接地
            if self.node_assigner:
                # 使用NodeAssigner获取comp2的节点对
                nodes = self.node_assigner.get_component_nodes(comp2.id, all_components)
                if nodes:
                    input_node, output_node = nodes
                    # 如果输出节点不是0，需要导线连接到接地
                    if output_node != 0:
                        return (output_node, 0)
            else:
                # 降级方案
                if node2 != 0:
                    return (node2, 0)
        
        elif comp2.type == ComponentType.GROUND:
            # comp1连接到接地
            if self.node_assigner:
                # 使用NodeAssigner获取comp1的节点对
                nodes = self.node_assigner.get_component_nodes(comp1.id, all_components)
                if nodes:
                    input_node, output_node = nodes
                    # 如果输出节点不是0，需要导线连接到接地
                    if output_node != 0:
                        return (output_node, 0)
            else:
                # 降级方案
                if node1 != 0:
                    return (node1, 0)
        
        # 规则2：非接地连接不需要导线
        # 元件之间的连接已经通过节点对正确表达
        return None
    
    def validate_netlist(self, netlist: str) -> Dict[str, Any]:
        """
        验证生成的网表是否有效
        
        返回: {'valid': bool, 'errors': List[str], 'warnings': List[str]}
        """
        errors = []
        warnings = []
        
        if not netlist or len(netlist.strip()) < 10:
            errors.append("网表为空或过短")
            return {'valid': False, 'errors': errors, 'warnings': warnings}
        
        lines = netlist.split('\n')
        
        # 检查是否有元件
        has_components = any(line.strip() and not line.strip().startswith('*') 
                           and not line.strip().startswith('.') 
                           for line in lines)
        if not has_components:
            errors.append("网表中没有元件")
        
        # 检查是否有电压源
        has_voltage_source = any(line.strip().startswith('V') for line in lines)
        if not has_voltage_source:
            warnings.append("网表中没有电压源")
        
        # 检查是否有分析指令
        has_analysis = any('.tran' in line or '.dc' in line or '.ac' in line 
                          for line in lines)
        if not has_analysis:
            errors.append("网表中没有分析指令")
        
        # 检查是否有.end
        has_end = any('.end' in line for line in lines)
        if not has_end:
            errors.append("网表缺少.end指令")
        
        return {
            'valid': len(errors) == 0,
            'errors': errors,
            'warnings': warnings
        }
